var classes = [
    {
        "name": "App\\Http\\Controllers\\Controller",
        "interface": false,
        "abstract": true,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 1,
        "loc": 5,
        "lloc": 4,
        "mi": 202.94,
        "mIwoC": 171,
        "commentWeight": 31.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.41,
        "afferentCoupling": 38,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Pegawai\\PegawaiController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 1,
        "length": 2,
        "vocabulary": 2,
        "volume": 2,
        "difficulty": 0.5,
        "effort": 1,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 1,
        "number_operands": 1,
        "number_operators_unique": 1,
        "number_operands_unique": 1,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 78.06,
        "mIwoC": 78.06,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "App\\Http\\Controllers\\Pegawai\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Pegawai\\PegawaiGajiController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "unduhSlipGaji",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 5,
        "ccnMethodMax": 4,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\Models\\Pegawai",
            "Carbon\\Carbon",
            "Carbon\\Carbon",
            "App\\Models\\Gaji",
            "App\\Models\\Gaji",
            "App\\Models\\Gaji",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\Models\\Pegawai",
            "Barryvdh\\DomPDF\\Facade\\Pdf"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 2,
        "length": 135,
        "vocabulary": 59,
        "volume": 794.16,
        "difficulty": 5.94,
        "effort": 4719.99,
        "level": 0.17,
        "bugs": 0.26,
        "time": 262,
        "intelligentContent": 133.62,
        "number_operators": 30,
        "number_operands": 105,
        "number_operators_unique": 6,
        "number_operands_unique": 53,
        "cloc": 22,
        "loc": 63,
        "lloc": 41,
        "mi": 83.48,
        "mIwoC": 43.84,
        "commentWeight": 39.64,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 324,
        "relativeDataComplexity": 0.26,
        "relativeSystemComplexity": 324.26,
        "totalStructuralComplexity": 648,
        "totalDataComplexity": 0.53,
        "totalSystemComplexity": 648.53,
        "package": "App\\Http\\Controllers\\Pegawai\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 7,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Pegawai\\PegawaiCutiController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 4,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\Models\\Cuti",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\Models\\Cuti",
            "App\\Models\\Cuti"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 3,
        "length": 69,
        "vocabulary": 30,
        "volume": 338.58,
        "difficulty": 5.4,
        "effort": 1828.31,
        "level": 0.19,
        "bugs": 0.11,
        "time": 102,
        "intelligentContent": 62.7,
        "number_operators": 15,
        "number_operands": 54,
        "number_operators_unique": 5,
        "number_operands_unique": 25,
        "cloc": 3,
        "loc": 35,
        "lloc": 32,
        "mi": 70.82,
        "mIwoC": 48.92,
        "commentWeight": 21.91,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 196,
        "relativeDataComplexity": 0.29,
        "relativeSystemComplexity": 196.29,
        "totalStructuralComplexity": 588,
        "totalDataComplexity": 0.87,
        "totalSystemComplexity": 588.87,
        "package": "App\\Http\\Controllers\\Pegawai\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Pegawai\\TugasPegawaiController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "show",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateStatus",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "storePengumpulan",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 10,
        "ccn": 7,
        "ccnMethodMax": 4,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\Models\\Tugas",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\Models\\Tugas",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\Models\\Tugas",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\Models\\Tugas",
            "App\\Models\\TugasPengumpulan"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 4,
        "length": 106,
        "vocabulary": 36,
        "volume": 548.01,
        "difficulty": 6.77,
        "effort": 3712.34,
        "level": 0.15,
        "bugs": 0.18,
        "time": 206,
        "intelligentContent": 80.9,
        "number_operators": 22,
        "number_operands": 84,
        "number_operators_unique": 5,
        "number_operands_unique": 31,
        "cloc": 15,
        "loc": 63,
        "lloc": 48,
        "mi": 77.51,
        "mIwoC": 43.21,
        "commentWeight": 34.3,
        "kanDefect": 0.5,
        "relativeStructuralComplexity": 225,
        "relativeDataComplexity": 0.33,
        "relativeSystemComplexity": 225.33,
        "totalStructuralComplexity": 900,
        "totalDataComplexity": 1.31,
        "totalSystemComplexity": 901.31,
        "package": "App\\Http\\Controllers\\Pegawai\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Pegawai\\PegawaiMeetingController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "show",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "App\\Models\\Meeting",
            "App\\Models\\Meeting"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 2,
        "length": 15,
        "vocabulary": 9,
        "volume": 47.55,
        "difficulty": 1.71,
        "effort": 81.51,
        "level": 0.58,
        "bugs": 0.02,
        "time": 5,
        "intelligentContent": 27.74,
        "number_operators": 3,
        "number_operands": 12,
        "number_operators_unique": 2,
        "number_operands_unique": 7,
        "cloc": 8,
        "loc": 22,
        "lloc": 14,
        "mi": 103.33,
        "mIwoC": 63.12,
        "commentWeight": 40.21,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.42,
        "relativeSystemComplexity": 25.42,
        "totalStructuralComplexity": 50,
        "totalDataComplexity": 0.83,
        "totalSystemComplexity": 50.83,
        "package": "App\\Http\\Controllers\\Pegawai\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Pegawai\\TugasPengumpulanController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\Models\\TugasPengumpulan",
            "App\\Models\\Tugas"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 1,
        "length": 51,
        "vocabulary": 25,
        "volume": 236.84,
        "difficulty": 2.8,
        "effort": 662.07,
        "level": 0.36,
        "bugs": 0.08,
        "time": 37,
        "intelligentContent": 84.72,
        "number_operators": 10,
        "number_operands": 41,
        "number_operators_unique": 3,
        "number_operands_unique": 22,
        "cloc": 7,
        "loc": 25,
        "lloc": 18,
        "mi": 92.41,
        "mIwoC": 55.86,
        "commentWeight": 36.55,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 100,
        "relativeDataComplexity": 0.27,
        "relativeSystemComplexity": 100.27,
        "totalStructuralComplexity": 100,
        "totalDataComplexity": 0.27,
        "totalSystemComplexity": 100.27,
        "package": "App\\Http\\Controllers\\Pegawai\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Pegawai\\PegawaiDashboardController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\Models\\Pegawai",
            "Carbon\\Carbon",
            "Carbon\\Carbon",
            "App\\Models\\Kehadiran",
            "App\\Models\\Kehadiran",
            "App\\Models\\Kehadiran",
            "App\\Models\\Kehadiran",
            "App\\Models\\Kehadiran",
            "App\\Models\\Gaji",
            "App\\Models\\Gaji",
            "App\\Models\\PengumumanPenerima"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 1,
        "length": 176,
        "vocabulary": 61,
        "volume": 1043.81,
        "difficulty": 5.44,
        "effort": 5676.86,
        "level": 0.18,
        "bugs": 0.35,
        "time": 315,
        "intelligentContent": 191.93,
        "number_operators": 21,
        "number_operands": 155,
        "number_operators_unique": 4,
        "number_operands_unique": 57,
        "cloc": 4,
        "loc": 44,
        "lloc": 40,
        "mi": 66.03,
        "mIwoC": 43.51,
        "commentWeight": 22.51,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 676,
        "relativeDataComplexity": 0.07,
        "relativeSystemComplexity": 676.07,
        "totalStructuralComplexity": 676,
        "totalDataComplexity": 0.07,
        "totalSystemComplexity": 676.07,
        "package": "App\\Http\\Controllers\\Pegawai\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 7,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Pegawai\\PegawaiPengumumanController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\Models\\PengumumanPenerima"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 1,
        "length": 42,
        "vocabulary": 15,
        "volume": 164.09,
        "difficulty": 3,
        "effort": 492.27,
        "level": 0.33,
        "bugs": 0.05,
        "time": 27,
        "intelligentContent": 54.7,
        "number_operators": 3,
        "number_operands": 39,
        "number_operators_unique": 2,
        "number_operands_unique": 13,
        "cloc": 2,
        "loc": 22,
        "lloc": 20,
        "mi": 78.49,
        "mIwoC": 55.97,
        "commentWeight": 22.51,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 100,
        "relativeDataComplexity": 0.09,
        "relativeSystemComplexity": 100.09,
        "totalStructuralComplexity": 100,
        "totalDataComplexity": 0.09,
        "totalSystemComplexity": 100.09,
        "package": "App\\Http\\Controllers\\Pegawai\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Pegawai\\PegawaiKehadiranController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 15,
        "ccn": 14,
        "ccnMethodMax": 13,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\Models\\Kehadiran",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth",
            "Carbon\\Carbon",
            "Carbon\\Carbon",
            "App\\Models\\Kehadiran",
            "App\\Models\\Kehadiran",
            "App\\Models\\Kehadiran"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 2,
        "length": 171,
        "vocabulary": 56,
        "volume": 993.06,
        "difficulty": 7.62,
        "effort": 7567.1,
        "level": 0.13,
        "bugs": 0.33,
        "time": 420,
        "intelligentContent": 130.32,
        "number_operators": 44,
        "number_operands": 127,
        "number_operators_unique": 6,
        "number_operands_unique": 50,
        "cloc": 1,
        "loc": 61,
        "lloc": 60,
        "mi": 48.2,
        "mIwoC": 38.34,
        "commentWeight": 9.85,
        "kanDefect": 0.85,
        "relativeStructuralComplexity": 784,
        "relativeDataComplexity": 0.38,
        "relativeSystemComplexity": 784.38,
        "totalStructuralComplexity": 1568,
        "totalDataComplexity": 0.76,
        "totalSystemComplexity": 1568.76,
        "package": "App\\Http\\Controllers\\Pegawai\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Auth\\NewPasswordController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\View\\View",
            "Illuminate\\Http\\Request",
            "Illuminate\\Http\\RedirectResponse",
            "Illuminate\\Http\\Request",
            "Illuminate\\Validation\\Rules\\Password",
            "Illuminate\\Support\\Facades\\Hash",
            "Illuminate\\Support\\Str",
            "Illuminate\\Auth\\Events\\PasswordReset",
            "Illuminate\\Support\\Facades\\Password"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 2,
        "length": 40,
        "vocabulary": 16,
        "volume": 160,
        "difficulty": 4.15,
        "effort": 664.62,
        "level": 0.24,
        "bugs": 0.05,
        "time": 37,
        "intelligentContent": 38.52,
        "number_operators": 4,
        "number_operands": 36,
        "number_operators_unique": 3,
        "number_operands_unique": 13,
        "cloc": 14,
        "loc": 31,
        "lloc": 17,
        "mi": 100.6,
        "mIwoC": 57.46,
        "commentWeight": 43.15,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 144,
        "relativeDataComplexity": 0.23,
        "relativeSystemComplexity": 144.23,
        "totalStructuralComplexity": 288,
        "totalDataComplexity": 0.46,
        "totalSystemComplexity": 288.46,
        "package": "App\\Http\\Controllers\\Auth\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 9,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Auth\\EmailVerificationPromptController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 1,
        "length": 5,
        "vocabulary": 4,
        "volume": 10,
        "difficulty": 0.67,
        "effort": 6.67,
        "level": 1.5,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 15,
        "number_operators": 1,
        "number_operands": 4,
        "number_operators_unique": 1,
        "number_operands_unique": 3,
        "cloc": 3,
        "loc": 11,
        "lloc": 8,
        "mi": 109.21,
        "mIwoC": 73.03,
        "commentWeight": 36.18,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 9.5,
        "totalStructuralComplexity": 9,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 9.5,
        "package": "App\\Http\\Controllers\\Auth\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Auth\\VerifyEmailController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__invoke",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\RedirectResponse",
            "Illuminate\\Foundation\\Auth\\EmailVerificationRequest",
            "Illuminate\\Auth\\Events\\Verified"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 1,
        "length": 14,
        "vocabulary": 6,
        "volume": 36.19,
        "difficulty": 4,
        "effort": 144.76,
        "level": 0.25,
        "bugs": 0.01,
        "time": 8,
        "intelligentContent": 9.05,
        "number_operators": 6,
        "number_operands": 8,
        "number_operators_unique": 3,
        "number_operands_unique": 3,
        "cloc": 3,
        "loc": 17,
        "lloc": 14,
        "mi": 93.97,
        "mIwoC": 63.68,
        "commentWeight": 30.29,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.6,
        "relativeSystemComplexity": 16.6,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 0.6,
        "totalSystemComplexity": 16.6,
        "package": "App\\Http\\Controllers\\Auth\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Auth\\PasswordResetLinkController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\View\\View",
            "Illuminate\\Http\\RedirectResponse",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Password"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 2,
        "length": 20,
        "vocabulary": 8,
        "volume": 60,
        "difficulty": 4.8,
        "effort": 288,
        "level": 0.21,
        "bugs": 0.02,
        "time": 16,
        "intelligentContent": 12.5,
        "number_operators": 4,
        "number_operands": 16,
        "number_operators_unique": 3,
        "number_operands_unique": 5,
        "cloc": 11,
        "loc": 25,
        "lloc": 14,
        "mi": 105.08,
        "mIwoC": 62.28,
        "commentWeight": 42.8,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.36,
        "relativeSystemComplexity": 36.36,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 0.71,
        "totalSystemComplexity": 72.71,
        "package": "App\\Http\\Controllers\\Auth\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Auth\\PasswordController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\RedirectResponse",
            "Illuminate\\Http\\Request",
            "Illuminate\\Validation\\Rules\\Password",
            "Illuminate\\Support\\Facades\\Hash"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 1,
        "length": 18,
        "vocabulary": 11,
        "volume": 62.27,
        "difficulty": 1.78,
        "effort": 110.7,
        "level": 0.56,
        "bugs": 0.02,
        "time": 6,
        "intelligentContent": 35.03,
        "number_operators": 2,
        "number_operands": 16,
        "number_operators_unique": 2,
        "number_operands_unique": 9,
        "cloc": 3,
        "loc": 13,
        "lloc": 10,
        "mi": 99.36,
        "mIwoC": 65.49,
        "commentWeight": 33.87,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.29,
        "relativeSystemComplexity": 36.29,
        "totalStructuralComplexity": 36,
        "totalDataComplexity": 0.29,
        "totalSystemComplexity": 36.29,
        "package": "App\\Http\\Controllers\\Auth\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Auth\\EmailVerificationNotificationController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\RedirectResponse",
            "Illuminate\\Http\\Request"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 1,
        "length": 9,
        "vocabulary": 6,
        "volume": 23.26,
        "difficulty": 1.5,
        "effort": 34.9,
        "level": 0.67,
        "bugs": 0.01,
        "time": 2,
        "intelligentContent": 15.51,
        "number_operators": 3,
        "number_operands": 6,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 3,
        "loc": 15,
        "lloc": 12,
        "mi": 98.56,
        "mIwoC": 66.62,
        "commentWeight": 31.94,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 25.5,
        "totalStructuralComplexity": 25,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 25.5,
        "package": "App\\Http\\Controllers\\Auth\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Auth\\AuthenticatedSessionController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\View\\View",
            "Illuminate\\Http\\RedirectResponse",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Validation\\ValidationException",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Http\\RedirectResponse",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 3,
        "length": 40,
        "vocabulary": 20,
        "volume": 172.88,
        "difficulty": 3.75,
        "effort": 648.29,
        "level": 0.27,
        "bugs": 0.06,
        "time": 36,
        "intelligentContent": 46.1,
        "number_operators": 10,
        "number_operands": 30,
        "number_operators_unique": 4,
        "number_operands_unique": 16,
        "cloc": 9,
        "loc": 41,
        "lloc": 32,
        "mi": 84.15,
        "mIwoC": 50.96,
        "commentWeight": 33.19,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 225,
        "relativeDataComplexity": 0.35,
        "relativeSystemComplexity": 225.35,
        "totalStructuralComplexity": 675,
        "totalDataComplexity": 1.06,
        "totalSystemComplexity": 676.06,
        "package": "App\\Http\\Controllers\\Auth\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Auth\\RegisteredUserController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\View\\View",
            "Illuminate\\Http\\RedirectResponse",
            "Illuminate\\Http\\Request",
            "Illuminate\\Validation\\Rules\\Password",
            "Illuminate\\Support\\Facades\\Hash",
            "App\\Models\\User",
            "Illuminate\\Auth\\Events\\Registered",
            "Illuminate\\Support\\Facades\\Auth"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 2,
        "length": 31,
        "vocabulary": 16,
        "volume": 124,
        "difficulty": 3.12,
        "effort": 386.31,
        "level": 0.32,
        "bugs": 0.04,
        "time": 21,
        "intelligentContent": 39.8,
        "number_operators": 4,
        "number_operands": 27,
        "number_operators_unique": 3,
        "number_operands_unique": 13,
        "cloc": 8,
        "loc": 24,
        "lloc": 16,
        "mi": 97.93,
        "mIwoC": 58.94,
        "commentWeight": 38.99,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.42,
        "relativeSystemComplexity": 25.42,
        "totalStructuralComplexity": 50,
        "totalDataComplexity": 0.83,
        "totalSystemComplexity": 50.83,
        "package": "App\\Http\\Controllers\\Auth\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 9,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Auth\\ConfirmablePasswordController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "show",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\View\\View",
            "Illuminate\\Http\\RedirectResponse",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Validation\\ValidationException"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 2,
        "length": 15,
        "vocabulary": 10,
        "volume": 49.83,
        "difficulty": 1.5,
        "effort": 74.74,
        "level": 0.67,
        "bugs": 0.02,
        "time": 4,
        "intelligentContent": 33.22,
        "number_operators": 3,
        "number_operands": 12,
        "number_operators_unique": 2,
        "number_operands_unique": 8,
        "cloc": 6,
        "loc": 22,
        "lloc": 16,
        "mi": 97.76,
        "mIwoC": 61.58,
        "commentWeight": 36.18,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.31,
        "relativeSystemComplexity": 49.31,
        "totalStructuralComplexity": 98,
        "totalDataComplexity": 0.63,
        "totalSystemComplexity": 98.63,
        "package": "App\\Http\\Controllers\\Auth\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Admin\\AdminController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 1,
        "length": 2,
        "vocabulary": 2,
        "volume": 2,
        "difficulty": 0.5,
        "effort": 1,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 1,
        "number_operands": 1,
        "number_operators_unique": 1,
        "number_operands_unique": 1,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 78.06,
        "mIwoC": 78.06,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "App\\Http\\Controllers\\Admin\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Admin\\TunjanganPotonganController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "App\\Models\\MasterTunjangan",
            "App\\Models\\MasterPotongan"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 1,
        "length": 14,
        "vocabulary": 9,
        "volume": 44.38,
        "difficulty": 1.57,
        "effort": 69.74,
        "level": 0.64,
        "bugs": 0.01,
        "time": 4,
        "intelligentContent": 28.24,
        "number_operators": 3,
        "number_operands": 11,
        "number_operators_unique": 2,
        "number_operands_unique": 7,
        "cloc": 4,
        "loc": 14,
        "lloc": 10,
        "mi": 103.35,
        "mIwoC": 66.52,
        "commentWeight": 36.83,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.2,
        "relativeSystemComplexity": 16.2,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 0.2,
        "totalSystemComplexity": 16.2,
        "package": "App\\Http\\Controllers\\Admin\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Admin\\PegawaiController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "edit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 9,
        "ccn": 4,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "App\\Models\\Pegawai",
            "App\\Models\\Jabatan",
            "App\\Models\\Pegawai",
            "App\\Models\\Jabatan",
            "App\\Models\\Divisi",
            "Illuminate\\Http\\Request",
            "Illuminate\\Validation\\Rules\\Password",
            "Illuminate\\Support\\Facades\\Hash",
            "App\\Models\\User",
            "Illuminate\\Support\\Facades\\DB",
            "App\\Models\\Pegawai",
            "App\\Models\\Jabatan",
            "App\\Models\\Divisi",
            "Illuminate\\Http\\Request",
            "App\\Models\\Pegawai",
            "Illuminate\\Validation\\Rule",
            "Illuminate\\Validation\\Rule",
            "Illuminate\\Validation\\Rules\\Password",
            "Illuminate\\Support\\Facades\\Hash",
            "Illuminate\\Support\\Facades\\DB",
            "App\\Models\\Pegawai",
            "Illuminate\\Support\\Facades\\DB"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 6,
        "length": 288,
        "vocabulary": 60,
        "volume": 1701.18,
        "difficulty": 11.95,
        "effort": 20336.89,
        "level": 0.08,
        "bugs": 0.57,
        "time": 1130,
        "intelligentContent": 142.3,
        "number_operators": 25,
        "number_operands": 263,
        "number_operators_unique": 5,
        "number_operands_unique": 55,
        "cloc": 6,
        "loc": 112,
        "lloc": 106,
        "mi": 50.21,
        "mIwoC": 32.66,
        "commentWeight": 17.55,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 900,
        "relativeDataComplexity": 0.23,
        "relativeSystemComplexity": 900.23,
        "totalStructuralComplexity": 5400,
        "totalDataComplexity": 1.35,
        "totalSystemComplexity": 5401.35,
        "package": "App\\Http\\Controllers\\Admin\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 10,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Admin\\MasterTunjanganController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "edit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "App\\Models\\MasterTunjangan",
            "App\\Models\\MasterTunjangan",
            "Illuminate\\Http\\Request",
            "App\\Models\\MasterTunjangan",
            "Illuminate\\Validation\\Rule",
            "App\\Models\\MasterTunjangan"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 6,
        "length": 50,
        "vocabulary": 22,
        "volume": 222.97,
        "difficulty": 2.1,
        "effort": 468.24,
        "level": 0.48,
        "bugs": 0.07,
        "time": 26,
        "intelligentContent": 106.18,
        "number_operators": 8,
        "number_operands": 42,
        "number_operators_unique": 2,
        "number_operands_unique": 20,
        "cloc": 6,
        "loc": 39,
        "lloc": 33,
        "mi": 78.84,
        "mIwoC": 50.3,
        "commentWeight": 28.55,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0.76,
        "relativeSystemComplexity": 64.76,
        "totalStructuralComplexity": 384,
        "totalDataComplexity": 4.56,
        "totalSystemComplexity": 388.56,
        "package": "App\\Http\\Controllers\\Admin\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Admin\\CutiController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateStatus",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "resetCutiTahunan",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 10,
        "ccn": 8,
        "ccnMethodMax": 8,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "App\\Models\\Cuti",
            "App\\Models\\Pegawai",
            "Illuminate\\Http\\Request",
            "App\\Models\\Cuti",
            "App\\Models\\SisaCuti",
            "Carbon\\Carbon",
            "Carbon\\Carbon",
            "App\\Models\\Kehadiran",
            "App\\Models\\Kehadiran",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\Models\\SisaCuti"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 3,
        "length": 167,
        "vocabulary": 60,
        "volume": 986.45,
        "difficulty": 10.15,
        "effort": 10016.27,
        "level": 0.1,
        "bugs": 0.33,
        "time": 556,
        "intelligentContent": 97.15,
        "number_operators": 35,
        "number_operands": 132,
        "number_operators_unique": 8,
        "number_operands_unique": 52,
        "cloc": 26,
        "loc": 92,
        "lloc": 66,
        "mi": 74.95,
        "mIwoC": 38.27,
        "commentWeight": 36.68,
        "kanDefect": 0.8,
        "relativeStructuralComplexity": 1156,
        "relativeDataComplexity": 0.17,
        "relativeSystemComplexity": 1156.17,
        "totalStructuralComplexity": 3468,
        "totalDataComplexity": 0.51,
        "totalSystemComplexity": 3468.51,
        "package": "App\\Http\\Controllers\\Admin\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 8,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Admin\\DivisiController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "edit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "App\\Models\\Divisi",
            "App\\Models\\Divisi",
            "Illuminate\\Http\\Request",
            "App\\Models\\Divisi",
            "Illuminate\\Validation\\Rule",
            "App\\Models\\Divisi"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 5,
        "length": 47,
        "vocabulary": 23,
        "volume": 212.61,
        "difficulty": 3.89,
        "effort": 828.05,
        "level": 0.26,
        "bugs": 0.07,
        "time": 46,
        "intelligentContent": 54.59,
        "number_operators": 10,
        "number_operands": 37,
        "number_operators_unique": 4,
        "number_operands_unique": 19,
        "cloc": 16,
        "loc": 48,
        "lloc": 32,
        "mi": 89.59,
        "mIwoC": 50.6,
        "commentWeight": 38.99,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 121,
        "relativeDataComplexity": 0.58,
        "relativeSystemComplexity": 121.58,
        "totalStructuralComplexity": 605,
        "totalDataComplexity": 2.92,
        "totalSystemComplexity": 607.92,
        "package": "App\\Http\\Controllers\\Admin\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Admin\\DashboardController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "App\\Models\\Pegawai",
            "App\\Models\\Gaji",
            "App\\Models\\Gaji",
            "App\\Models\\Jabatan",
            "Carbon\\Carbon",
            "Illuminate\\Support\\Facades\\DB",
            "Illuminate\\Support\\Facades\\DB",
            "Illuminate\\Support\\Facades\\DB",
            "Illuminate\\Support\\Facades\\DB",
            "Illuminate\\Support\\Facades\\DB",
            "Illuminate\\Support\\Facades\\DB",
            "Illuminate\\Support\\Facades\\DB",
            "Illuminate\\Support\\Facades\\DB",
            "App\\Models\\Pengumuman",
            "App\\Models\\Meeting"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 1,
        "length": 101,
        "vocabulary": 55,
        "volume": 583.92,
        "difficulty": 2.48,
        "effort": 1448.56,
        "level": 0.4,
        "bugs": 0.19,
        "time": 80,
        "intelligentContent": 235.38,
        "number_operators": 15,
        "number_operands": 86,
        "number_operators_unique": 3,
        "number_operands_unique": 52,
        "cloc": 6,
        "loc": 29,
        "lloc": 23,
        "mi": 83.05,
        "mIwoC": 50.66,
        "commentWeight": 32.39,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 1024,
        "relativeDataComplexity": 0.03,
        "relativeSystemComplexity": 1024.03,
        "totalStructuralComplexity": 1024,
        "totalDataComplexity": 0.03,
        "totalSystemComplexity": 1024.03,
        "package": "App\\Http\\Controllers\\Admin\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 8,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Admin\\JabatanController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "edit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "App\\Models\\Jabatan",
            "Illuminate\\Http\\Request",
            "App\\Models\\Jabatan",
            "App\\Models\\Jabatan",
            "Illuminate\\Http\\Request",
            "App\\Models\\Jabatan",
            "Illuminate\\Validation\\Rule",
            "App\\Models\\Jabatan"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 6,
        "length": 75,
        "vocabulary": 24,
        "volume": 343.87,
        "difficulty": 2.86,
        "effort": 984.72,
        "level": 0.35,
        "bugs": 0.11,
        "time": 55,
        "intelligentContent": 120.08,
        "number_operators": 12,
        "number_operands": 63,
        "number_operators_unique": 2,
        "number_operands_unique": 22,
        "cloc": 22,
        "loc": 71,
        "lloc": 49,
        "mi": 83.2,
        "mIwoC": 45.24,
        "commentWeight": 37.97,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 196,
        "relativeDataComplexity": 0.47,
        "relativeSystemComplexity": 196.47,
        "totalStructuralComplexity": 1176,
        "totalDataComplexity": 2.8,
        "totalSystemComplexity": 1178.8,
        "package": "App\\Http\\Controllers\\Admin\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Admin\\MeetingController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "edit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "App\\Models\\Meeting",
            "App\\Models\\Pegawai",
            "Illuminate\\Http\\Request",
            "App\\Models\\Meeting",
            "Illuminate\\Support\\Facades\\DB",
            "App\\Models\\Meeting",
            "App\\Models\\Pegawai",
            "Illuminate\\Http\\Request",
            "App\\Models\\Meeting",
            "Illuminate\\Support\\Facades\\DB",
            "App\\Models\\Meeting"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 6,
        "length": 136,
        "vocabulary": 36,
        "volume": 703.11,
        "difficulty": 3.56,
        "effort": 2502.24,
        "level": 0.28,
        "bugs": 0.23,
        "time": 139,
        "intelligentContent": 197.57,
        "number_operators": 15,
        "number_operands": 121,
        "number_operators_unique": 2,
        "number_operands_unique": 34,
        "cloc": 24,
        "loc": 69,
        "lloc": 45,
        "mi": 83.45,
        "mIwoC": 43.87,
        "commentWeight": 39.59,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 289,
        "relativeDataComplexity": 0.38,
        "relativeSystemComplexity": 289.38,
        "totalStructuralComplexity": 1734,
        "totalDataComplexity": 2.28,
        "totalSystemComplexity": 1736.28,
        "package": "App\\Http\\Controllers\\Admin\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Admin\\AdminTugasPengumpulanController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateStatus",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 5,
        "ccnMethodMax": 5,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "App\\Models\\TugasPengumpulan",
            "App\\Models\\Jabatan",
            "App\\Models\\Tim",
            "App\\Models\\Divisi",
            "Illuminate\\Http\\Request",
            "App\\Models\\TugasPengumpulan"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 2,
        "length": 153,
        "vocabulary": 48,
        "volume": 854.5,
        "difficulty": 5.95,
        "effort": 5088.15,
        "level": 0.17,
        "bugs": 0.28,
        "time": 283,
        "intelligentContent": 143.5,
        "number_operators": 22,
        "number_operands": 131,
        "number_operators_unique": 4,
        "number_operands_unique": 44,
        "cloc": 10,
        "loc": 56,
        "lloc": 46,
        "mi": 72.97,
        "mIwoC": 42.53,
        "commentWeight": 30.44,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 576,
        "relativeDataComplexity": 0.14,
        "relativeSystemComplexity": 576.14,
        "totalStructuralComplexity": 1152,
        "totalDataComplexity": 0.28,
        "totalSystemComplexity": 1152.28,
        "package": "App\\Http\\Controllers\\Admin\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Admin\\MasterPotonganController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "edit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "App\\Models\\MasterPotongan",
            "App\\Models\\MasterPotongan",
            "Illuminate\\Http\\Request",
            "App\\Models\\MasterPotongan",
            "Illuminate\\Validation\\Rule",
            "App\\Models\\MasterPotongan"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 6,
        "length": 50,
        "vocabulary": 22,
        "volume": 222.97,
        "difficulty": 2.1,
        "effort": 468.24,
        "level": 0.48,
        "bugs": 0.07,
        "time": 26,
        "intelligentContent": 106.18,
        "number_operators": 8,
        "number_operands": 42,
        "number_operators_unique": 2,
        "number_operands_unique": 20,
        "cloc": 17,
        "loc": 54,
        "lloc": 37,
        "mi": 87.41,
        "mIwoC": 49.21,
        "commentWeight": 38.19,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0.76,
        "relativeSystemComplexity": 64.76,
        "totalStructuralComplexity": 384,
        "totalDataComplexity": 4.56,
        "totalSystemComplexity": 388.56,
        "package": "App\\Http\\Controllers\\Admin\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Admin\\GajiMassalController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "langkahSatu",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "langkahDua",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "simpan",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "cekGajiSudahAda",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 10,
        "ccn": 7,
        "ccnMethodMax": 6,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "App\\Models\\Pegawai",
            "Carbon\\Carbon",
            "Carbon\\Carbon",
            "Carbon\\Carbon",
            "App\\Models\\Pegawai",
            "App\\Models\\Divisi",
            "App\\Models\\Tim",
            "App\\Models\\Jabatan",
            "Illuminate\\Http\\Request",
            "App\\Models\\Pegawai",
            "App\\Models\\MasterTunjangan",
            "App\\Models\\MasterPotongan",
            "Illuminate\\Http\\Request",
            "App\\Models\\Gaji",
            "Illuminate\\Support\\Facades\\DB",
            "Illuminate\\Http\\Request",
            "App\\Models\\Pegawai"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 4,
        "length": 252,
        "vocabulary": 90,
        "volume": 1635.95,
        "difficulty": 8.98,
        "effort": 14693.96,
        "level": 0.11,
        "bugs": 0.55,
        "time": 816,
        "intelligentContent": 182.14,
        "number_operators": 39,
        "number_operands": 213,
        "number_operators_unique": 7,
        "number_operands_unique": 83,
        "cloc": 8,
        "loc": 75,
        "lloc": 67,
        "mi": 60.95,
        "mIwoC": 36.72,
        "commentWeight": 24.23,
        "kanDefect": 0.91,
        "relativeStructuralComplexity": 2025,
        "relativeDataComplexity": 0.11,
        "relativeSystemComplexity": 2025.11,
        "totalStructuralComplexity": 8100,
        "totalDataComplexity": 0.43,
        "totalSystemComplexity": 8100.43,
        "package": "App\\Http\\Controllers\\Admin\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 11,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Admin\\PengumumanController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "App\\Models\\Pengumuman",
            "App\\Models\\Pegawai",
            "App\\Models\\Jabatan",
            "App\\Models\\Tim",
            "App\\Models\\Divisi",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\Models\\Pengumuman",
            "Illuminate\\Support\\Facades\\DB",
            "App\\Models\\Pengumuman"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 4,
        "length": 74,
        "vocabulary": 38,
        "volume": 388.35,
        "difficulty": 3.59,
        "effort": 1393.48,
        "level": 0.28,
        "bugs": 0.13,
        "time": 77,
        "intelligentContent": 108.23,
        "number_operators": 13,
        "number_operands": 61,
        "number_operators_unique": 4,
        "number_operands_unique": 34,
        "cloc": 17,
        "loc": 60,
        "lloc": 43,
        "mi": 82.41,
        "mIwoC": 45.7,
        "commentWeight": 36.71,
        "kanDefect": 0.52,
        "relativeStructuralComplexity": 400,
        "relativeDataComplexity": 0.21,
        "relativeSystemComplexity": 400.21,
        "totalStructuralComplexity": 1600,
        "totalDataComplexity": 0.86,
        "totalSystemComplexity": 1600.86,
        "package": "App\\Http\\Controllers\\Admin\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 9,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Admin\\TimDivisiController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "App\\Models\\Divisi"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 1,
        "length": 7,
        "vocabulary": 6,
        "volume": 18.09,
        "difficulty": 1.25,
        "effort": 22.62,
        "level": 0.8,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 14.48,
        "number_operators": 2,
        "number_operands": 5,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 4,
        "loc": 13,
        "lloc": 9,
        "mi": 108.12,
        "mIwoC": 70.25,
        "commentWeight": 37.87,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.2,
        "relativeSystemComplexity": 16.2,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 0.2,
        "totalSystemComplexity": 16.2,
        "package": "App\\Http\\Controllers\\Admin\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Admin\\TimController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "edit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "App\\Models\\Divisi",
            "Illuminate\\Http\\Request",
            "App\\Models\\Tim",
            "App\\Models\\Tim",
            "App\\Models\\Divisi",
            "Illuminate\\Http\\Request",
            "App\\Models\\Tim",
            "App\\Models\\Tim"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 5,
        "length": 55,
        "vocabulary": 23,
        "volume": 248.8,
        "difficulty": 4.53,
        "effort": 1126.13,
        "level": 0.22,
        "bugs": 0.08,
        "time": 63,
        "intelligentContent": 54.97,
        "number_operators": 12,
        "number_operands": 43,
        "number_operators_unique": 4,
        "number_operands_unique": 19,
        "cloc": 16,
        "loc": 50,
        "lloc": 34,
        "mi": 87.97,
        "mIwoC": 49.55,
        "commentWeight": 38.42,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 121,
        "relativeDataComplexity": 0.58,
        "relativeSystemComplexity": 121.58,
        "totalStructuralComplexity": 605,
        "totalDataComplexity": 2.92,
        "totalSystemComplexity": 607.92,
        "package": "App\\Http\\Controllers\\Admin\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Admin\\AdminTugasController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "App\\Models\\Tugas",
            "App\\Models\\Pegawai",
            "App\\Models\\Jabatan",
            "App\\Models\\Tim",
            "App\\Models\\Divisi",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\Models\\Tugas",
            "Illuminate\\Support\\Facades\\Log",
            "Illuminate\\Support\\Facades\\Log"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 2,
        "length": 160,
        "vocabulary": 59,
        "volume": 941.22,
        "difficulty": 6.53,
        "effort": 6144.09,
        "level": 0.15,
        "bugs": 0.31,
        "time": 341,
        "intelligentContent": 144.19,
        "number_operators": 19,
        "number_operands": 141,
        "number_operators_unique": 5,
        "number_operands_unique": 54,
        "cloc": 4,
        "loc": 49,
        "lloc": 45,
        "mi": 63.99,
        "mIwoC": 42.58,
        "commentWeight": 21.42,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 841,
        "relativeDataComplexity": 0.2,
        "relativeSystemComplexity": 841.2,
        "totalStructuralComplexity": 1682,
        "totalDataComplexity": 0.4,
        "totalSystemComplexity": 1682.4,
        "package": "App\\Http\\Controllers\\Admin\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 9,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Admin\\AdminKehadiranController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "show",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "downloadBukti",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "App\\Models\\Kehadiran",
            "App\\Models\\Kehadiran",
            "App\\Models\\Pegawai",
            "Illuminate\\Http\\Request",
            "App\\Models\\Pegawai",
            "App\\Models\\Kehadiran",
            "App\\Models\\Kehadiran",
            "Illuminate\\Support\\Facades\\Storage"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 3,
        "length": 115,
        "vocabulary": 32,
        "volume": 575,
        "difficulty": 4.86,
        "effort": 2795.69,
        "level": 0.21,
        "bugs": 0.19,
        "time": 155,
        "intelligentContent": 118.26,
        "number_operators": 21,
        "number_operands": 94,
        "number_operators_unique": 3,
        "number_operands_unique": 29,
        "cloc": 12,
        "loc": 56,
        "lloc": 44,
        "mi": 77.28,
        "mIwoC": 44.42,
        "commentWeight": 32.86,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 841,
        "relativeDataComplexity": 0.21,
        "relativeSystemComplexity": 841.21,
        "totalStructuralComplexity": 2523,
        "totalDataComplexity": 0.63,
        "totalSystemComplexity": 2523.63,
        "package": "App\\Http\\Controllers\\Admin\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Admin\\LaporanPerformaController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "unduhPdf",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fetchPerformanceData",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 17,
        "ccn": 15,
        "ccnMethodMax": 15,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "App\\Models\\Divisi",
            "App\\Models\\Tim",
            "App\\Models\\Pegawai",
            "Illuminate\\Http\\Request",
            "Barryvdh\\DomPDF\\Facade\\Pdf",
            "Illuminate\\Support\\Str",
            "Illuminate\\Http\\Request",
            "Carbon\\Carbon",
            "Carbon\\Carbon",
            "Carbon\\Carbon",
            "Carbon\\Carbon",
            "Carbon\\Carbon",
            "Carbon\\Carbon",
            "Carbon\\Carbon",
            "Carbon\\Carbon",
            "Carbon\\Carbon",
            "Carbon\\Carbon",
            "App\\Models\\Pegawai",
            "App\\Models\\Divisi",
            "App\\Models\\Tim",
            "App\\Models\\Pegawai",
            "App\\Models\\Kehadiran",
            "Carbon\\Carbon",
            "Carbon\\Carbon",
            "Carbon\\Carbon",
            "Carbon\\Carbon"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 1,
        "length": 340,
        "vocabulary": 105,
        "volume": 2282.84,
        "difficulty": 16.03,
        "effort": 36598.35,
        "level": 0.06,
        "bugs": 0.76,
        "time": 2033,
        "intelligentContent": 142.39,
        "number_operators": 66,
        "number_operands": 274,
        "number_operators_unique": 11,
        "number_operands_unique": 94,
        "cloc": 0,
        "loc": 86,
        "lloc": 86,
        "mi": 32.27,
        "mIwoC": 32.27,
        "commentWeight": 0,
        "kanDefect": 0.72,
        "relativeStructuralComplexity": 3136,
        "relativeDataComplexity": 0.09,
        "relativeSystemComplexity": 3136.09,
        "totalStructuralComplexity": 9408,
        "totalDataComplexity": 0.28,
        "totalSystemComplexity": 9408.28,
        "package": "App\\Http\\Controllers\\Admin\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 9,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Admin\\GajiController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "edit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "unduhSlipGaji",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "cekGajiPegawai",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 8,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 8,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 18,
        "ccn": 11,
        "ccnMethodMax": 5,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "App\\Models\\Gaji",
            "App\\Models\\Jabatan",
            "Carbon\\Carbon",
            "Carbon\\Carbon",
            "Carbon\\Carbon",
            "Carbon\\Carbon",
            "App\\Models\\Pegawai",
            "App\\Models\\Pegawai",
            "App\\Models\\MasterTunjangan",
            "App\\Models\\MasterPotongan",
            "Illuminate\\Http\\Request",
            "App\\Models\\Gaji",
            "Illuminate\\Support\\Facades\\DB",
            "App\\Models\\Gaji",
            "App\\Models\\Pegawai",
            "App\\Models\\MasterTunjangan",
            "App\\Models\\MasterPotongan",
            "Illuminate\\Http\\Request",
            "App\\Models\\Gaji",
            "Illuminate\\Support\\Facades\\DB",
            "App\\Models\\Gaji",
            "App\\Models\\Gaji",
            "Barryvdh\\DomPDF\\Facade\\Pdf",
            "Illuminate\\Http\\Request",
            "App\\Models\\Gaji",
            "App\\Models\\Pegawai"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 8,
        "length": 346,
        "vocabulary": 87,
        "volume": 2229.26,
        "difficulty": 12.6,
        "effort": 28088.66,
        "level": 0.08,
        "bugs": 0.74,
        "time": 1560,
        "intelligentContent": 176.93,
        "number_operators": 58,
        "number_operands": 288,
        "number_operators_unique": 7,
        "number_operands_unique": 80,
        "cloc": 15,
        "loc": 124,
        "lloc": 109,
        "mi": 56.29,
        "mIwoC": 30.63,
        "commentWeight": 25.66,
        "kanDefect": 1.49,
        "relativeStructuralComplexity": 2304,
        "relativeDataComplexity": 0.18,
        "relativeSystemComplexity": 2304.18,
        "totalStructuralComplexity": 18432,
        "totalDataComplexity": 1.47,
        "totalSystemComplexity": 18433.47,
        "package": "App\\Http\\Controllers\\Admin\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 10,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\ProfileController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "edit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\View\\View",
            "Illuminate\\Http\\Request",
            "Illuminate\\Http\\RedirectResponse",
            "App\\Http\\Requests\\ProfileUpdateRequest",
            "Illuminate\\Support\\Facades\\Redirect",
            "Illuminate\\Http\\RedirectResponse",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth",
            "Illuminate\\Support\\Facades\\Redirect"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "implements": [],
        "lcom": 3,
        "length": 32,
        "vocabulary": 14,
        "volume": 121.84,
        "difficulty": 3.55,
        "effort": 431.96,
        "level": 0.28,
        "bugs": 0.04,
        "time": 24,
        "intelligentContent": 34.36,
        "number_operators": 6,
        "number_operands": 26,
        "number_operators_unique": 3,
        "number_operands_unique": 11,
        "cloc": 9,
        "loc": 36,
        "lloc": 27,
        "mi": 88.87,
        "mIwoC": 53.9,
        "commentWeight": 34.97,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 196,
        "relativeDataComplexity": 0.27,
        "relativeSystemComplexity": 196.27,
        "totalStructuralComplexity": 588,
        "totalDataComplexity": 0.8,
        "totalSystemComplexity": 588.8,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.02,
        "afferentCoupling": 0,
        "efferentCoupling": 7,
        "instability": 1,
        "violations": {}
    }
]